[package]
name = "pos-install"
version = "0.1.0"
authors = ["Michael Birch <birchmd@casperlabs.io>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]
bench = false
doctest = false
test = false

[features]
std = ["contract/std", "types/std"]
enable-bonding = ["pos/enable-bonding"]

[dependencies]
base16 = { version = "0.2.1", default-features = false }
contract = { path = "../../../contract", package = "casperlabs-contract" }
pos = { path = "../pos", default-features = false, features = ["lib"] }
proof-of-stake = { path = "../../../proof-of-stake", package = "casperlabs-proof-of-stake" }
types = { path = "../../../types", package = "casperlabs-types" }
